sudo: false
group: travis_latest
language: cpp

compiler:
  - gcc

env:
  matrix:
    - FUZZ=1
    - CCMLW=0
    - CCMLW=1
    - CCMNOEVENT=1
  global:
    - ACE_ROOT=$TRAVIS_BUILD_DIR/ext/ATCD/ACE
    - TAO_ROOT=$TRAVIS_BUILD_DIR/ext/ATCD/TAO
    - CIAO_ROOT=$TRAVIS_BUILD_DIR
    - DANCE_ROOT=$TRAVIS_BUILD_DIR/ext/DAnCE
    - MPC_ROOT=$TRAVIS_BUILD_DIR/ext/MPC
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$LD_LIBRARY_PATH
    - COMPILER=g++-8

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxerces-c-dev
            - libssl-dev
            - g++-6
      env: COMPILER=g++-6 CCMLW=0 CCMNOEVENT=0
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxerces-c-dev
            - libssl-dev
            - g++-7
      env: COMPILER=g++-7 CCMLW=0 CCMNOEVENT=0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libssl-dev
      - libxerces-c-dev
      - g++-8

before_install:
  - mkdir ext
  - cd ext && git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - git clone --depth 1 git://github.com/DOCGroup/DAnCE.git
  - git clone --depth 1 git://github.com/DOCGroup/ACE_TAO.git ATCD
  - cd ..

branches:
  only:
    - master

before_script:
  - export
  - echo -e "#include \"ace/config-linux.h\"" >> $ACE_ROOT/ace/config.h
  - echo -e "workspace {\n\$(TAO_ROOT)/TAO_ACE.mwc\n\$(TAO_ROOT)/tests/Hello\n" >> $TRAVIS_BUILD_DIR/travis.mwc
  - echo -e "\$(CIAO_ROOT)/CIAO_TAO_DAnCE.mwc\n" >> $TRAVIS_BUILD_DIR/travis.mwc
  - echo -e "}\n" >> $TRAVIS_BUILD_DIR/travis.mwc
  - if [ "$CCMLW" == "1" ]; then echo -e "ccm_lw=1" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features; fi
  - if [ "$CCMNOEVENT" == "1" ]; then echo -e "ccm_noevent=1" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features; fi
  - echo -e "inline=0\noptimize=0\nxerces3=1\nssl=1\nipv6=1\n" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU
  - echo -e "xerces3=1\nssl=1\n" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features
  - echo -e "TAO/tests/Hello/run_test.pl" >> $TAO_ROOT/bin/travis-ci.lst
  - if [ "$CXX" == "g++" ]; then echo -e "c++11=1\n" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - if [ "$CXX" == "g++" ]; then echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - if [ "$CXX" == "clang++" ]; then echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - cat $TRAVIS_BUILD_DIR/travis.mwc
  - cat $ACE_ROOT/bin/MakeProjectCreator/config/default.features
  - cat $ACE_ROOT/ace/config.h
  - cat $ACE_ROOT/include/makeinclude/platform_macros.GNU
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

script:
  - if [ "$FUZZ" == "1" ]; then exec perl $ACE_ROOT/bin/fuzz.pl; fi
  - perl $ACE_ROOT/bin/mwc.pl -type gnuace -workers 6 travis.mwc
  - make -j 6
  - perl $ACE_ROOT/bin/auto_run_tests.pl -l $TAO_ROOT/bin/travis-ci.lst

