branches:
  only:
    - master

os: Visual Studio 2017

clone_depth: 15

install:
  - mkdir ext && cd ext
  - git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - git clone --depth 1 git://github.com/DOCGroup/ACE_TAO.git
  - git clone --depth 1 git://github.com/DOCGroup/DAnCE.git
  - cd ..
  - set MPC_ROOT=%CD%\ext\MPC
  - set ACE_ROOT=%CD%\ext\ACE_TAO\ACE
  - set TAO_ROOT=%CD%\ext\ACE_TAO\TAO
  - set CIAO_ROOT=%CD%
  - set DANCE_ROOT=%CD%\ext\DAnCE
  - set PATH=%ACE_ROOT%\lib:%PATH%
  - ps: $CONTENT='#include "ace/config-win32.h"'
  - ps: $CONTENT > ext\ACE_TAO\ACE\ace\config.h
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - call perl %ACE_ROOT%\bin\mwc.pl -type vs2017 %CIAO_ROOT%\CIAO_TAO_DAnCE.mwc

platform:
  - x64

configuration:
  - Debug

build:
  parallel: true
  project: CIAO_TAO_DAnCE.sln

test: off
