branches:
  only:
    - master

environment:
  MPC_ROOT: ${APPVEYOR_BUILD_FOLDER}\ext\MPC
  ACE_ROOT: ${APPVEYOR_BUILD_FOLDER}\ext\ACE_TAO\ACE
  TAO_ROOT: ${APPVEYOR_BUILD_FOLDER}\ext\ACE_TAO\TAO
  CIAO_ROOT: ${APPVEYOR_BUILD_FOLDER}
  DANCE_ROOT: ${APPVEYOR_BUILD_FOLDER}\ext\DAnCE
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MPC_TYPE: vc14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MPC_TYPE: vs2017

clone_depth: 5

install:
  - cmd: if "%platform%"=="Win32" set VCPKG_ARCH=x86-windows
  - cmd: if "%platform%"=="x64"   set VCPKG_ARCH=x64-windows
  - cmd: vcpkg remove --outdated --recurse
  - cmd: vcpkg install --recurse --triplet %VCPKG_ARCH% xerces-c openssl
  - cmd: vcpkg integrate install
  - cmd: mkdir ext && cd ext
  - git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - git clone --depth 1 git://github.com/DOCGroup/ACE_TAO.git
  - git clone --depth 1 git://github.com/DOCGroup/DAnCE.git
  - cd ..
  - set PATH=%ACE_ROOT%\lib:%PATH%
  - ps: |
      echo "#include ""ace/config-win32.h""" | out-file -encoding ASCII ext\ACE_TAO\ACE\ace\config.h
  - ps: |
      cat ext\ACE_TAO\ACE\bin\MakeProjectCreator\config\default.features
  - perl %ACE_ROOT%\bin\mwc.pl -type %MPC_TYPE% %CIAO_ROOT%\CIAO_TAO_DAnCE.mwc

platform:
  - x64

configuration:
  - Debug

build:
  parallel: true
  project: CIAO_TAO_DAnCE.sln

cache:
  - c:\tools\vcpkg\installed\

test: off
